### ISSUE TITLE
Problem 1

### ISSUE THREAD

**Issue by itsRealM12C** [throwaway96/dejavuln-autoroot#13]
Hello! When we put the folder to the USB drive on a PC, and we ejected it, and we plugged the USB to the TV, and when i opened the music app and USB drive, and it said "the file is empty.". My TV Model: 32LM6300PLA My TV Software Version: 05.40.20

**Comment by jockyw2001** [comment]
Worked fine on my tv:
LG 50UM7600PTA (50 UM7600PTAg)
Firmware version = 05.40.20
webOS 4.10.0
OTA ID = HE_DTV_W19P_AFADABAA
OTAID = W19P
SoC = k5lp

**Comment by itsRealM12C** [comment]
When i checked cani.rootmy.tv, it said it will work.
I wonder how its working for you very well.
The reason was probably instart service menu or idk.
Please help me.

**Comment by throwaway96** [comment]
User error. W19R 05.40.20 is vulnerable.

**Comment by itsRealM12C** [comment]
wth

**Comment by itsRealM12C** [comment]
The another LG TV did show the music file but mine not.

**Comment by throwaway96** [comment]
@itsRealM12C 

You have provided zero evidence that there is anything wrong with dejavuln-autoroot. W19R 05.40.20 is definitely vulnerable, and the script is known to work on webOS 4.10.0. Read the README carefully and try again.

If you continue with the meaningless/low-value posts, you will be blocked. You have already worn my patience quite thin with your behavior on Discord. Nobody has forgotten about that just because you moved to GitHub.

If you want to contribute positively to the community, you will need to put in significantly more effort. Especially given your previous record, you should refrain from repeatedly posting low-effort "ideas" without having done any research.

**Comment by itsRealM12C** [comment]
Bro im being nice you just guys are- bruh.

**Comment by itsRealM12C** [comment]
Just good.

**Comment by throwaway96** [comment]
Stop posting multiple times in a row. You can edit posts.

**Comment by itsRealM12C** [comment]
I am very apologize for mistake. The only mistake i made was i added 1 folder instead of all. I don't need help anymore because my TV is rooted successfully.
