### ISSUE TITLE
Is there an app or mod that can enable recording rca and rf analogue tv?

### ISSUE THREAD

**Issue by 03stevensmi** [throwaway96/dejavuln-autoroot#21]
I know different modules/regions have this feature enabled. Some only have analogue rf recording support and not composite recording, most have none, and very few have both.

My question is,
Is it possible to use this root method to ether install an app (if one exists)
Or tweak the TV to enable analogue TV capture for rf aerial and rca (composite) capture?

My LG TV supports only taking screenshot pictures of analogue signals but that's it.

Once my LG is rooted,
Does anyone know if re enabling this feature is possible?

If so, how.
Any help would be amazing as I can't find anything regarding this limitation anywhere online
Other than people asking this very same question.

Please, If you a way of method,
Please let us know.

Cheers
03stsvensmi

**Comment by throwaway96** [comment]
You don't even need root to change the region in the EZ-Adjust menu. See [`webos-ssap-web`](https://github.com/throwaway96/webos-ssap-web) for a method of opening service menus without a service remote.

But **be careful** changing the region, because once you change to certain regions (e.g., EU), you can't change back. (The details depend on webOS version.)

With root, you could presumably also enable features at a lower level without changing the region. But that would likely involve a bit of reverse engineering.
