### ISSUE TITLE
TV unrooted after restart 

### ISSUE THREAD

**Issue by YaBoiDan** [throwaway96/dejavuln-autoroot#26]
I have re-rooted my TV following an update to 06.10.50 using this method, but after a second reboot, I lose the Homebrew channel and any apps I've installed from there, and SSH is no longer active.

Some additional weirdness in case related, once I have run the file via the music player, I get a success message and the Homebrew channel appears. At this point, I cannot install anything until I reboot the TV. Upon the first reboot, everything is as expected, I can install, ssh shows as an open port etc.

Once or twice I've had the Homebrew app icon disappear, but it still shows the coloured tile and as an installed app, it does not launch however. 

Model: 49UJ630V-ZA
WEBOS TV Version: 3.9.2-62912

Any help would be appreciated, cheers!

**Comment by Polo753** [comment]
Hello, I have the same issue with an OLED55B7V rooted on an old firmware using CrashD.
I updated to version 6.10.45 so that Plex works again.

The root installation works, and with Homebrew, I can install Picap and HyperHDR and launch them, but once the TV restarts, the Homebrew icon disappears, and it's impossible to launch the installed apps.

I've tried several times, but the root is not permanent.

**Comment by YaBoiDan** [comment]
I did it for Plex too! I cracked it though, my old root method left files behind, I think it was something to do with Dev mode based on the file name I saw it drop when trying the old method again. Ended up doing a factory reset of the TV, followed the steps again, perma root once again.... Just in time for my Chromecast to arrive 🙃
Hope that helps!

@throwaway96, I suspect you may have a few people coming off the back of the Plex certificate antics, could be worth an update to the README to tell people to factory reset or if you know what dev files to remove, get rid of those.
