### ISSUE TITLE
usb mounting problems

### ISSUE THREAD

**Issue by A-n-g-e-l-o** [throwaway96/dejavuln-autoroot#9]
I don't know if your program is where this is suppose to get fixed so it works after the autorooting, but there is an issue with mounting / read write of usb devices. This problem does not occur if you use the normal developer account and app from LG

reason for using usb is for Kodi and backing up files on external usb.

I tried like for hours to figure out why it isn't working, because it does work with normal LG developer mode.

I found this on an another website how to solve it, but I think if this is corrected where its suppose to than people would appreciate. specially people who don't know how to work with terminal/ssh

Hope this helps and thanks in advance...

" I was trying to install my root certificate and I run into the same issue you described:
1649876022007.png
Setting rw flag for the emmc device did not seem to help.
1649876275006.png

Then I run into this gist:
https://gist.github.com/Informatic/1983f2e501444cf1cbd182e50820d6c1#injecting-mitmproxy-ca

it described how to remount the
Code:
/etc/ssl/certs
directory in RW mode. I was then able to add my cert to the root bundle.
So check the gist out, I think this is what you are looking for."

**Comment by throwaway96** [comment]
> I don't know if your program is where this is suppose to get fixed so it works after the autorooting

This is not relevant to dejavuln-autoroot. Depending on what the problem actually is, it sounds more closely related to Kodi or *maybe* Homebrew Channel.

> there is an issue with mounting / read write of usb devices

What issue exactly? From the context, I guess you're trying to access USB drives (via `/tmp/usb`) from within Kodi. (People also try to install Kodi itself to USB drives.)

Do you encounter the same problem with other applications? You haven't provided any information about your webOS version, SoC, etc.

> This problem does not occur if you use the normal developer account and app from LG

I suspect there was some confounding factor involved, as I don't see how root would affect the way USB drives are mounted inside jails. Maybe there is some mechanism, but I really can't think of what it might be.

> I found this on an another website how to solve it

Sorry, but I don't understand what you're proposing here. If you have a more detailed explanation, I'm willing to consider it.

By the way, never try to modify any of the read-only partitions. Remounting them read/write will fail because they're squashfs, but the fact that people are even trying means they must have missed all the warnings that what they're trying to do **will** brick their TVs.

**Comment by A-n-g-e-l-o** [comment]
Yeah, I’m very sorry, i’m really a novice, I just assume that if the same app is installed the same way on the same platform and device , but difference is that the mounting doesn’t work, then it has to be the rooting of the device… it’s an LG tv G3 , it is for accessing the tmp/ sda1 folder on Kodi, I’ve installed from the home brew channel after installing the homebrew from the official developer app on my Mac… it does work without any flaws or problems…
